name: Sync to Hugging Face Hub

on:
  push:
    branches: [main] # or your main branch name

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true # If you have large files
      - name: Push to Hugging Face Space Interface
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }} # Reference the GitHub secret
        run: |
          git config --global user.email anjalimittal.bvcoe@gmail.com
          git config --global user.name Anjali-Mittal
          git remote add hf https://huggingface.co/spaces/Anjali3Mittal/book_recommmendations
          git push hf main
